routes/web.php
<?php

use App\Http\Controllers\AdminCategoryController;
use App\Http\Controllers\AdminPostController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\NewsletterController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\SessionsController;
use App\Http\Controllers\UpdatesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::prefix('admin')
        ->middleware('admin')
        ->as('admin.')
        ->group(function () {
            Route::controller(PostController::class)
                ->prefix('/posts')
                ->as('posts.')
                ->group(function () {
                    Route::get('create', 'create')->name('create');
                    Route::post('', 'store')->name('store');
                    Route::patch('{post}', 'update')->name('update');
                    Route::delete('{post}', 'destroy')->name('destroy');
                });

            Route::controller(AdminPostController::class)
                ->prefix('/posts')
                ->as('posts.')
                ->group(function () {
                    Route::get('', 'index')->name('index');
                    Route::get('{post}/edit', 'edit')->name('edit');
                });

            Route::controller(AdminCategoryController::class)
                ->prefix('/categories')
                ->as('categories.')
                ->group(function () {
                    Route::get('', 'index')->name('index');
                    Route::get('create', 'create')->name('create');
                    Route::post('', 'store')->name('store');
                    Route::get('edit/{category:slug}', 'edit')->name('edit');
                    Route::patch('category/{category:slug}', 'update')->name('update');
                    Route::delete('category/{category:slug}', 'destroy')->name('destroy');
                });
        });

    Route::post('posts/{post:slug}/comments', [CommentController::class, 'store'])
        ->name('posts.comments');

    Route::post('like', [LikeController::class, 'like'])->name('like');
    Route::delete('like', [LikeController::class, 'unlike'])->name('unlike');

    Route::post('logout', [SessionsController::class, 'destroy'])
        ->name('logout');
});

Route::group(['middleware' => 'guest'], function () {
    Route::get('register', [RegisterController::class, 'create'])
        ->name('register.create');

    Route::post('register', [RegisterController::class, 'store'])
        ->name('register.store');

    Route::get('login', [SessionsController::class, 'create'])
        ->name('login.create');

    Route::post('login', [SessionsController::class, 'authenticate'])
        ->name('login.authenticate');
});

Route::get('/', [PostController::class, 'index'])->name('home');
Route::get('posts/{post:slug}', [PostController::class, 'show'])
    ->name('post.show');

Route::post('newsletter', NewsletterController::class)
    ->name('newsletter');

Route::get('updates', UpdatesController::class)->name('updates');

app/Models/Post.php
<?php

namespace App\Models;

use App\Contracts\Likeable;
use App\Models\Concerns\Likes;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Post extends Model implements Likeable
{
    use HasFactory, Likes;

    protected $fillable = [
        'title',
        'excerpt',
        'body',
        'user_id',
        'thumbnail',
        'published_at',
    ];

    protected $casts = [
        'published_at' => 'datetime',
    ];

    protected $with = [
        'categories',
        'author',
    ];

    protected static function booted()
    {
        parent::booted();

        static::created(function ($post) {
            $post->slug = Str::slug($post->title).'-'.$post->id;
            $post->save();
        });

        static::updating(function ($post) {
            $post->slug = Str::slug($post->title).'-'.$post->id;
        });
    }

    public function getThumbnailAttribute($thumbnail): string
    {
        return ! empty($thumbnail) ? "/storage/{$thumbnail}" : '/images/illustration-1.png';
    }

    /**
     * Scope a query to only include published posts.
     *
     * @param  Builder  $query
     * @return Builder
     */
    public function scopePublished(Builder $query): Builder
    {
        return $query->whereNotNull('published_at');
    }

    /**
     * Scope a query to only include posts based on search.
     *
     * @param  Builder  $query
     * @param  array  $filters
     * @return Builder
     */
    public function scopeFilter(Builder $query, array $filters): Builder
    {
        $query->when(
            $filters['search'] ?? false,
            fn ($query, $search) => $query->where(
                fn ($query) => $query->where('title', 'like', "%{$search}%")
                    ->orWhere('excerpt', 'like', "%{$search}%")
            )
        );

        $query->when(
            $filters['category'] ?? false,
            fn ($query, $category) => $query->whereHas('categories', fn ($query) => $query->where('slug', $category))
        );

        $query->when(
            $filters['author'] ?? false,
            fn ($query, $author) => $query->whereHas('author', fn ($query) => $query->where('username', $author))
        );

        return $query;
    }

    public function categories(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Category::class, with(new CategoryPost)->getTable(), 'post_id', 'category_id')
            ->withTimestamps();
    }

    public function author(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function comments(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Comment::class);
    }

    public function isPublished(): bool
    {
        return $this->published_at !== null;
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePostRequest;
use App\Http\Requests\UpdatePostRequest;
use App\Models\Post;
use Carbon\Carbon;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(): View|Factory|Application
    {
        return view('posts.index', [
            'posts' => Post::latest('published_at')
                ->published()
                ->filter(request()->only(['search', 'category', 'author']))
                ->paginate(6)
                ->withQueryString(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create(): Application|Factory|View
    {
        return view('admin.posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StorePostRequest  $request
     * @return RedirectResponse
     */
    public function store(StorePostRequest $request): RedirectResponse
    {
        $attributes = $request->validated();

        $attributes['user_id'] = auth()->user()->id;

        if ($attributes['thumbnail'] ?? false) {
            $attributes['thumbnail'] = request()->file('thumbnail')->store('thumbnails');
        }

        $attributes['published_at'] = Carbon::now();

        $post = Post::create($attributes);

        $post->categories()->attach($attributes['categories']);

        return redirect("posts/{$post->slug}")->with([
            'success' => 'A new post has been published',
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  Post  $post
     * @return Application|Factory|View
     */
    public function show(Post $post): View|Factory|Application
    {
        abort_if(! $post->isPublished(), 404);

        return view('posts.show', [
            'post' => $post->load([
                'comments' => function ($query) {
                    $query->orderByDesc('created_at');
                },
                'comments.author',
            ]),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdatePostRequest  $request
     * @param  Post  $post
     * @return RedirectResponse
     */
    public function update(UpdatePostRequest $request, Post $post): RedirectResponse
    {
        $attributes = $request->validated();

        if ($attributes['thumbnail'] ?? false) {
            Storage::delete($post->thumbnail);
            $attributes['thumbnail'] = request()->file('thumbnail')->store('thumbnails');
        }

        if (array_key_exists('is_published', $attributes)
            && $attributes['is_published'] == 1
            && ! $post->isPublished()) {
            //only publish the post if the post is unpublished
            $attributes['published_at'] = Carbon::now();
        } elseif (array_key_exists('is_published', $attributes) && $attributes['is_published'] == 0) {
            //remove the post from published status
            $attributes['published_at'] = null;
        }

        $post->update($attributes);

        if (array_key_exists('categories', $attributes)) {
            $post->categories()->sync($attributes['categories']);
        }

        return redirect()->back()->with('success', 'The post has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Post  $post
     * @return RedirectResponse
     *
     * @throws \Throwable
     */
    public function destroy(Post $post): RedirectResponse
    {
        $post->categories()->detach();
        $post->deleteOrFail();

        return redirect()
            ->back()
            ->with([
                'success' => 'Post has been deleted.',
            ]);
    }
}

resources/views/admin/posts/create.blade.php
<x-layout>
    <x-setting-page heading="Publish New Post">
        <form method="POST"
              action="{{ route('admin.posts.store') }}"
              enctype="multipart/form-data"
              x-data="data()"
              x-init="initQuill()" ,
              x-on:submit="submit()"
        >
            @csrf

            <x-form.input name='title' required/>
            <x-form.file name="thumbnail" required/>

            <div class="py-2">
                <x-form.quill name="excerpt"/>
            </div>

            <div class="py-2">
                <x-form.quill name="body"/>
            </div>

            <div class="mb-6">
                <label class="block mb-2 uppercase font-bold text-xs text-gray-700"
                       for="categories"
                >
                    Categories
                </label>
                <select class="border border-gray-400 p-2 w-full"
                        name="categories[]"
                        id="categories"
                        multiple
                >
                    @php
                        $categories = \App\Models\Category::all()->sortBy('name');
                    @endphp

                    @foreach ($categories as $category)
                        <option
                            value="{{ $category->id }}"
                            {{ old('categories') && in_array($category->id, old('categories')) ? 'selected' : '' }}>
                            {{ ucwords($category->name) }}
                        </option>
                    @endforeach
                </select>

                <x-form.error name="categories"/>
            </div>

            <x-form.submit-button>Publish</x-form.submit-button>
        </form>
    </x-setting-page>
    @push('scripts')
        <script>
            function data () {
                return {
                    initQuill () {
                        new Quill(this.$refs.quillExcerpt, quillOptions)
                        new Quill(this.$refs.quillBody, quillOptions)
                    },
                    submit () {
                        this.$refs.excerpt.value = this.$refs.quillExcerpt.__quill.root.innerHTML
                        this.$refs.body.value = this.$refs.quillBody.__quill.root.innerHTML

                        if (isQuillEmpty(this.$refs.quillExcerpt.__quill)) {
                            this.$refs.excerpt.value = ''
                        }

                        if (isQuillEmpty(this.$refs.quillBody.__quill)) {
                            this.$refs.body.value = ''
                        }
                    }
                }
            }
        </script>
    @endpush
</x-layout>

resources/views/admin/posts/edit.blade.php
<x-layout>
    <x-setting-page heading="Edit Post">
        <article class="text-right pt-1 pb-2">
            <a href="{{ route('post.show', $post->slug) }}"
               class="text-sm no-underline text-blue-600 hover:underline hover:text-blue-500"
               target="_blank">{{ route('post.show', $post->slug) }}</a>
        </article>
        <form method="POST"
              action="{{ url("admin/posts/{$post->id}") }}"
              enctype="multipart/form-data"
              x-data="data()"
              x-init="initQuill()"
              x-on:submit="submit()"
        >
            @csrf
            @method('PATCH')

            <x-form.input name='title' value="{{ old('title', $post->title) }}"/>
            <div class="flex mt-6">
                <div class="flex-auto w-10/12">
                    <x-form.file name="thumbnail"/>
                </div>

                <img src="{{ asset($post->thumbnail) }}"
                     alt="{{ $post->title }} thumbnail"
                     class="rounded-xl ml-4 flex-auto w-2/12"/>
            </div>

            <div class="py-2">
                <x-form.quill name="excerpt">{!! $post->excerpt !!}</x-form.quill>
            </div>

            <div class="py-2">
                <x-form.quill name="body">{!! $post->body !!}</x-form.quill>
            </div>

            <div>
                <label class="block mb-2 uppercase font-bold text-xs text-gray-700"
                       for="categories"
                >
                    Categories
                </label>
                <select class="border border-gray-400 p-2 w-full"
                        name="categories[]"
                        id="categories"
                        multiple
                >
                    @php
                        $categories = \App\Models\Category::all()->sortBy('name');
                    @endphp

                    @foreach ($categories as $category)
                        <option
                            value="{{ $category->id }}"
                            {{ old('categories', $post->categories->pluck('id')->toArray()) && in_array($category->id, old('categories', $post->categories->pluck('id')->toArray())) ? 'selected' : '' }}>
                            {{ ucwords($category->name) }}
                        </option>
                    @endforeach
                </select>

                <x-form.error name="categories"/>
            </div>

            <div class="mb-6">
                <x-form.toggle name="is_published" toggle="{{ $post->isPublished() ? 1 : 0 }}"/>
            </div>

            <x-form.submit-button>Update</x-form.submit-button>
        </form>
    </x-setting-page>

    @push('scripts')
        <script>
            function data () {
                return {
                    initQuill () {
                        new Quill(this.$refs.quillExcerpt, quillOptions)
                        new Quill(this.$refs.quillBody, quillOptions)
                    },
                    submit () {
                        this.$refs.excerpt.value = this.$refs.quillExcerpt.__quill.root.innerHTML
                        this.$refs.body.value = this.$refs.quillBody.__quill.root.innerHTML

                        if (isQuillEmpty(this.$refs.quillExcerpt.__quill)) {
                            this.$refs.excerpt.value = ''
                        }

                        if (isQuillEmpty(this.$refs.quillBody.__quill)) {
                            this.$refs.body.value = ''
                        }
                    }
                }
            }
        </script>
    @endpush
</x-layout>

resources/views/admin/posts/index.blade.php
<x-layout>
    <x-setting-page heading="Manage Posts">
        <div class="flex flex-col">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-200">
                            <tbody class="bg-white divide-y divide-gray-200">
                            @foreach ($posts as $post)
                                <tr>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <div class="flex items-center">
                                            <div class="ml-4">
                                                <div class="text-sm font-medium text-gray-900">
                                                    <a href="{{ url("posts/{$post->slug}") }}" target="_blank">
                                                        {{ $post->title }}
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </td>

                                    <td class="px-6 py-4 whitespace-nowrap">
                                        @if ($post->isPublished())
                                            <span
                                                class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                            Published
                                                </span>
                                        @else
                                            <span
                                                class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                            Unpublished
                                            </span>
                                        @endif
                                    </td>

                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{{ url("admin/posts/{$post->id}/edit") }}" class="text-blue-500
                                        hover:text-blue-600">Edit</a>
                                    </td>

                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <form method="POST"
                                              action="{{ url("admin/posts/{$post->id}") }}"
                                              x-data="{ confirmPostDeletion: false}"
                                              @submit.prevent="if(confirmPostDeletion) $el.submit()"
                                        >
                                            @csrf
                                            @method('DELETE')

                                            <button class="text-xs text-gray-400"
                                                    type="submit"
                                                    @click="confirmPostDeletion = confirm('Are you sure you want to delete {{ $post->title }}')">
                                                Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <footer class="mt-4 p-4">
                            {{ $posts->links() }}
                        </footer>
                    </div>
                </div>
            </div>
        </div>
    </x-setting-page>
</x-layout>