routes/web.php
<?php

use App\Http\Controllers\AdminCategoryController;
use App\Http\Controllers\AdminPostController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\NewsletterController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\SessionsController;
use App\Http\Controllers\UpdatesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::prefix('admin')
        ->middleware('admin')
        ->as('admin.')
        ->group(function () {
            Route::controller(PostController::class)
                ->prefix('/posts')
                ->as('posts.')
                ->group(function () {
                    Route::get('create', 'create')->name('create');
                    Route::post('', 'store')->name('store');
                    Route::patch('{post}', 'update')->name('update');
                    Route::delete('{post}', 'destroy')->name('destroy');
                });

            Route::controller(AdminPostController::class)
                ->prefix('/posts')
                ->as('posts.')
                ->group(function () {
                    Route::get('', 'index')->name('index');
                    Route::get('{post}/edit', 'edit')->name('edit');
                });

            Route::controller(AdminCategoryController::class)
                ->prefix('/categories')
                ->as('categories.')
                ->group(function () {
                    Route::get('', 'index')->name('index');
                    Route::get('create', 'create')->name('create');
                    Route::post('', 'store')->name('store');
                    Route::get('edit/{category:slug}', 'edit')->name('edit');
                    Route::patch('category/{category:slug}', 'update')->name('update');
                    Route::delete('category/{category:slug}', 'destroy')->name('destroy');
                });
        });

    Route::post('posts/{post:slug}/comments', [CommentController::class, 'store'])
        ->name('posts.comments');

    Route::post('like', [LikeController::class, 'like'])->name('like');
    Route::delete('like', [LikeController::class, 'unlike'])->name('unlike');

    Route::post('logout', [SessionsController::class, 'destroy'])
        ->name('logout');
});

Route::group(['middleware' => 'guest'], function () {
    Route::get('register', [RegisterController::class, 'create'])
        ->name('register.create');

    Route::post('register', [RegisterController::class, 'store'])
        ->name('register.store');

    Route::get('login', [SessionsController::class, 'create'])
        ->name('login.create');

    Route::post('login', [SessionsController::class, 'authenticate'])
        ->name('login.authenticate');
});

Route::get('/', [PostController::class, 'index'])->name('home');
Route::get('posts/{post:slug}', [PostController::class, 'show'])
    ->name('post.show');

Route::post('newsletter', NewsletterController::class)
    ->name('newsletter');

Route::get('updates', UpdatesController::class)->name('updates');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Str;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'slug'];

    protected static function booted()
    {
        parent::booted();

        static::created(function ($category) {
            $category->slug = Str::slug($category->name.' '.$category->id);
            $category->save();
        });

        static::updating(function ($category) {
            $category->slug = Str::slug($category->name.' '.$category->id);
        });
    }

    public function posts(): BelongsToMany
    {
        return $this->belongsToMany(Post::class, with(new CategoryPost)->getTable(), 'category_id', 'post_id');
    }
}

app/Http/Controllers/AdminCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Models\Category;

class AdminCategoryController extends Controller
{
    public function index()
    {
        return view('admin.categories.index', [
            'categories' => Category::latest()
                ->withCount('posts')
                ->paginate(50),
        ]);
    }

    public function create(Category $category)
    {
        return view('admin.categories.create', [
            'category' => $category,
        ]);
    }

    public function store(StoreCategoryRequest $request)
    {
        Category::create($request->validated());

        return back()->with(['success' => 'A new category has been saved.']);
    }

    public function edit(Category $category)
    {
        return view('admin.categories.edit', [
            'category' => $category,
        ]);
    }

    public function update(Category $category, UpdateCategoryRequest $request)
    {
        $category->update($request->validated());
        $category = $category->refresh();

        return redirect(route('admin.categories.edit', $category))
            ->with(['success' => 'Category has been updated.']);
    }

    public function destroy(Category $category)
    {
        if ($category->posts()->count() > 0) {
            return back()
                ->with(['error' => 'Category has posts.']);
        }

        $category->deleteOrFail();

        return back()
            ->with(['success' => 'Category has been deleted.']);
    }
}

resources/views/admin/categories/create.blade.php
<x-layout>
    <x-setting-page heading="Create New Category">
        <form method="POST" action="{{ route('admin.categories.store') }}" enctype="multipart/form-data">
            @csrf

            <x-form.input name='name' required/>

            <x-form.submit-button>Save</x-form.submit-button>
        </form>
    </x-setting-page>
</x-layout>

resources/views/admin/categories/edit.blade.php
<x-layout>
    <x-setting-page heading="Edit Category">
        <form method="POST" action="{{ route('admin.categories.update', $category) }}" enctype="multipart/form-data">
            @csrf
            @method('PATCH')

            <x-form.input name='name' value="{{ old('name', $category->name) }}" required/>

            <x-form.submit-button>Update</x-form.submit-button>
        </form>
    </x-setting-page>
</x-layout>

resources/views/admin/categories/index.blade.php
<x-layout>
    <x-setting-page heading="Manage Categories">
        <div class="flex flex-col">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-200">
                            <tbody class="bg-white divide-y divide-gray-200">
                            @foreach ($categories as $category)
                                <tr>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <div class="flex items-center">
                                            <div class="ml-4">
                                                <div class="text-sm font-medium text-gray-900">
                                                    <a href="{{ url("posts/{$category->slug}") }}" target="_blank">
                                                        {{ $category->name }}
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </td>

                                    <td class="px-6 py-4 whitespace-nowrap">
                                    <span
                                        class="px-2 inline-flex text-xs leading-5 font-semibold text-gray-800">
                                        {{ $category->posts_count }}
                                    </span>
                                    </td>

                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{{ url(route('admin.categories.edit', $category)) }}" class="text-blue-500
                                        hover:text-blue-600">Edit</a>
                                    </td>

                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <form method="POST"
                                              action="{{ route('admin.categories.destroy', $category) }}"
                                              x-data="{ confirmCategoryDeletion: false}"
                                              @submit.prevent="if(confirmCategoryDeletion) $el.submit()"
                                        >
                                            @csrf
                                            @method('DELETE')

                                            <button class="text-xs text-gray-400"
                                                    type="submit"
                                                    @click="confirmCategoryDeletion = confirm('Are you sure you want to delete {{ $category->title }}')">
                                                Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </x-setting-page>
</x-layout>